const data = [
  {
    responsive_id: '',
    id: 95,
    full_name: 'Edwina Ebsworth',
    email: 'eebsworth2m@sbwire.com',
    start_date: '09/27/2021',
    money: 19586.23,
    age: '27',
    experience: '2 Years',
    status: 1,
  },
  {
    responsive_id: '',
    id: 1,
    full_name: "Korrie O'Crevy",
    email: 'kocrevy0@thetimes.co.uk',
    start_date: '09/23/2021',
    money: 23896.35,
    age: '61',
    experience: '1 Year',
    status: 2,
  },
  {
    responsive_id: '',
    id: 7,
    full_name: 'Eileen Diehn',
    email: 'ediehn6@163.com',
    start_date: '10/15/2021',
    money: 18991.67,
    age: '59',
    experience: '9 Years',
    status: 3,
  },
  {
    responsive_id: '',
    id: 11,
    full_name: 'De Falloon',
    email: 'dfalloona@ifeng.com',
    start_date: '06/12/2021',
    money: 19252.12,
    age: '30',
    experience: '0 Year',
    status: 4,
  },
  {
    responsive_id: '',
    id: 3,
    full_name: 'Stella Ganderton',
    email: 'sganderton2@tuttocitta.it',
    start_date: '03/24/2021',
    money: 13076.28,
    age: '66',
    experience: '6 Years',
    status: 5,
  },
  {
    responsive_id: '',
    id: 5,
    full_name: 'Harmonia Nisius',
    email: 'hnisius4@gnu.org',
    start_date: '08/25/2021',
    money: 10909.52,
    age: '33',
    experience: '3 Years',
    status: 2,
  },
  {
    responsive_id: '',
    id: 6,
    full_name: 'Genevra Honeywood',
    email: 'ghoneywood5@narod.ru',
    start_date: '06/01/2021',
    money: 17803.8,
    age: '61',
    experience: '1 Year',
    status: 1,
  },
  {
    responsive_id: '',
    id: 4,
    full_name: 'Dorolice Crossman',
    email: 'dcrossman3@google.co.jp',
    start_date: '12/03/2021',
    money: 12336.17,
    age: '22',
    experience: '2 Years',
    status: 2,
  },
]

export default data
